version: '3.5'
services:
  pymix:
    image: pymix
    privileged: true
    restart: unless-stopped
    container_name: "pymix"
    #user: "501:20"
    #networks:
    #  - subbox-bridge
    ports:
      - 8002:8002
    volumes:
      - ./db:/pymix/db
      - private-updownloads:/private/updownloads
      - private-sorted:/private-sorted
      - private-staged:/private-staged
      - public-uploads:/public/uploads
      - /Users/lukepurnell/workspace/subbox:/subbox
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_ENVIRONMENT=dev
#networks:
#  subbox-bridge:
#    external: true
#    name: subbox-bridge
volumes:
  private-updownloads:
    external: true
    name: private-updownloads
  private-staged:
    driver: local
    name: private-staged
  public-uploads:
    external: true
    name: public-uploads
  private-sorted:
    driver: local
    name: private-sorted