version: '3.5'
services:
  pymix:
    image: pymix
    privileged: true
    restart: unless-stopped
    container_name: "pymix"
    #user: "501:20"
    networks:
      - subbox-bridge
    ports:
      - 8002:8002
    volumes:
      - ./db:/pymix/db
      - /Users/lukepurnell/subbox:/subbox
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_ENVIRONMENT=prod
networks:
  subbox-bridge:
    external: true
    name: subbox-bridge
