---
app_env: dev
rekordbox:
  xml_path: /Users/lukepurnell/workspace/subbox/rekordbox/rekordbox_empty.xml
  zip_name: 'subbox-export'
containers:
  subsonic:
    host: http://localhost:4533
    username: emc
    version: 1.16.1
    music_path_base_to_remove: music
    serving_music_path_base: /Users/lukepurnell/workspace/subbox/private/{user}/nav_music
    docker_compose_file: /Users/lukepurnell/workspace/subbox/docker-compose/navidrome/docker-compose.yml
    env_file: /Users/lukepurnell/workspace/subbox/docker-compose/navidrome/env
  filebrowser:
    data: /Users/lukepurnell/workspace/subbox/docker-compose/filebrowser/data/users/{user}/private
    data_public: /Users/lukepurnell/workspace/subbox/docker-compose/filebrowser/data/users/{user}/public
    docker_compose_file: /Users/lukepurnell/workspace/subbox/docker-compose/filebrowser/docker-compose.yml
    env_file: /Users/lukepurnell/workspace/subbox/docker-compose/filebrowser/env
  beets:
    host: http://localhost:8337
    data: /Users/lukepurnell/workspace/subbox/private/{user}/beets/download
    data_public: /Users/lukepurnell/workspace/subbox/public/beets/download
    docker_compose_file: /Users/lukepurnell/workspace/subbox/docker-compose/beets/docker-compose.yml
    env_file: /Users/lukepurnell/workspace/subbox/docker-compose/beets/env
    config_file_src: /Users/lukepurnell/workspace/subbox/beets/config/config.yaml
    config_file_dst: /Users/lukepurnell/workspace/subbox/{user}/beets/config/config.yaml
    example_music:
      path: /Users/lukepurnell/workspace/subbox/beets/example_music
      search_id: 63d2a9f9-9951-4bed-b402-317d00b8943a
logs_directory: logs
user_root: /Users/lukepurnell/workspace/subbox/private/{user}
db:
  path: /Users/lukepurnell/PycharmProjects/pymix/db/user_db.json
max_number_of_users: 10
max_number_of_tracks: 1000
# number of seconds after which the export job will be updated with number of files written to zip during export job
update_job_period_s: 1