---
app_env: prod
rekordbox:
  xml_path: /subbox/rekordbox/rekordbox_empty.xml
  zip_name: music
containers:
  subsonic:
    #host: http://localhost:4533/navidrome
    host: http://navidrome{user}:4533
    version: 1.161
    music_path_base_to_remove: /music
    serving_music_path_base: /private-music
    music_backup_path: /private-music/backup/{user}
    docker_compose_file: /subbox/docker-compose/navidrome/docker-compose.yml
    env_file: /subbox/docker-compose/navidrome/env
    config_file_dst: /subbox/users/{user}/data/navidrome.toml
  filebrowser:
    user_root: /user-updownloads
    data_watch: /user-updownloads/{user}/watch
    data_uploads: /user-updownloads/{user}/uploads
    data_downloads: /user-updownloads/{user}/downloads
    docker_compose_file: /subbox/docker-compose/filebrowser/docker-compose.yml
    env_file: /subbox/docker-compose/filebrowser/env
  beets:
    host: http://beets{user}:{port}
    data: /private-staged/{user}/
    data_public: /public-staged
    docker_compose_file: /subbox/docker-compose/beets/docker-compose.yml
    env_file: /subbox/docker-compose/beets/env
    config_file_dst: /subbox/users/{user}/beets/config/config.yaml
logs_directory: logs
user_root: /subbox/{user}
db:
  host: pymix-postgres
  port: 5432
max_number_of_users: 10
max_number_of_tracks: 1000
max_library_size: 10737418240 # 10GB
# number of seconds after which the export job will be updated with number of files written to zip during export job
update_job_period_s: 2
subsonic:
  host: http:/localhost:4533
  username: lajp
  version: 1.16.1